version: "3.1"

services:
  gitlab:
    restart: always
    image: gitlab/gitlab-ce:latest
    hostname: 192.168.204.132
    ports:
    - 443:443
    - 80:80
    - 23:22
    volumes:
    - ./gitlab/config:/etc/gitlab
    - ./gitlab/logs:/var/log/gitlab
    - ./gitlab/data:/var/opt/gitlab
    environment:
      GITLAB_BACKUP_SCHEDULE: daily
      GITLAB_BACKUP_TIME: 03:00
  
  # gitlab-runner:
  #  container_name: gitlab-runner
  #  image: gitlab/gitlab-runner:latest
  #  volumes:
  #    - ./gitlab-runner/data:/home/gitlab_ci_multi_runner/data
  #    - ./gitlab-runner/config:/etc/gitlab-runner
  #    - /var/run/docker.sock:/var/run/docker.sock:rw
  #  restart: always