version: "2"
services:
  # nginx:
  #   restart: always
  #   image: nginx:latest
  #   container_name: nginx
  #   volumes:
  #     - "./nginx/nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro"
  #     - "./nginx/nginx-conf/gitlab-http.conf:/etc/nginx/conf.d/gitlab-http.conf:ro"
  #     - "./nginx/nginx-logs:/var/log/nginx"
  #   network_mode: "bridge"
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - gitlab_app
  #   links:
  #     - gitlab_app
  gitlab_app:
    restart: always
    image: "gitlab/gitlab-ce:latest"
    hostname: "192.168.50.132"
    container_name: gitlab_app
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        #external_url 'https://192.168.50.132/'
        gitlab_rails['gitlab_signup_enabled'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = 8022

        # gitlab_rails['db_adapter'] = "postgresql"
        # gitlab_rails['db_database'] = "gitlabhq_production"
        # gitlab_rails['db_username'] = "git"
        # gitlab_rails['db_password'] = "T0pS3cr3T"
        # gitlab_rails['db_host'] = "postgresql"
        # gitlab_rails['db_port'] = 5432
        # gitlab_rails['redis_host'] = "redis"
        # gitlab_rails['redis_port'] = 6379
        # gitlab_rails['redis_database'] = 0
        # gitlab_workhorse['enable'] = true
        # gitlab_workhorse['listen_network'] = "tcp"
        # gitlab_workhorse['listen_addr'] = "0.0.0.0:8081"
        # gitlab_workhorse['auth_backend'] = "http://localhost:8080"
        # unicorn['listen'] = '127.0.0.1'
        # unicorn['port'] = 8080
        # postgresql['enable'] = false
        # redis['enable'] = false
        # nginx['enable'] = false
    expose:
      - "8081"
    volumes:
      - "./gitlab/gitlab-config:/etc/gitlab"
      - "./gitlab/gitlab-data:/var/opt/gitlab"
      - "./gitlab/gitlab-logs:/var/log/gitlab"
    network_mode: "bridge"
    ports:
      - "8022:22"
    depends_on:
      - postgresql
      - redis
    links:
      - postgresql
      - redis
  postgresql:
    restart: always
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_DB: gitlabhq_production
      POSTGRES_USER: git
      POSTGRES_PASSWORD: T0pS3cr3T
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - "./postgresql/postgresql-data:/var/lib/postgresql/data"
    network_mode: "bridge"
  redis:
    restart: always
    image: redis:latest
    container_name: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - "./redis/redis-data:/data"
    network_mode: "bridge"
