version: "3.1"

services:
  gitlab:
    restart: always
    image: gitlab/gitlab-ce:latest
    ports:
      - 443:443
      - 80:80
      - 23:22
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab

  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    volumes:
      - ./gitlab-runner/data:/home/gitlab_ci_multi_runner/data
      - ./gitlab-runner/config:/etc/gitlab-runner
      - ./gitlab-runner/run/docker.sock:/var/run/docker.sock:rw
    restart: always
